-- remove existing rows
TRUNCATE classes_students CASCADE;

-- insert into join table
INSERT INTO classes_students (class_id, student_id)
VALUES
  ((SELECT id FROM classes WHERE subject = 'Underwater Basket Weaving'),
   (SELECT id FROM students WHERE first_name = 'Adam')),
  ((SELECT id FROM classes WHERE subject = 'Happiness'),
    (SELECT id FROM students WHERE first_name = 'Gina')),
  ((SELECT id FROM classes WHERE subject = 'Underwater Basket Weaving'),
    (SELECT id FROM students WHERE first_name = 'Gina')),
  ((SELECT id FROM classes WHERE subject = 'Light Treason'),
    (SELECT id FROM students WHERE first_name = 'Sam')),
  ((SELECT id FROM classes WHERE subject = 'Happiness'),
    (SELECT id FROM students WHERE first_name = 'Tommy')),
  ((SELECT id FROM classes WHERE subject = 'Light Treason'),
    (SELECT id FROM students WHERE first_name = 'Jordon')),
  ((SELECT id FROM classes WHERE subject = 'Flossing'),
    (SELECT id FROM students WHERE first_name = 'George')),
  ((SELECT id FROM classes WHERE subject = 'Underwater Basket Weaving'),
   (SELECT id FROM students WHERE first_name = 'Akiko')),
  ((SELECT id FROM classes WHERE subject = 'Happiness'),
    (SELECT id FROM students WHERE first_name = 'Sam')),
  ((SELECT id FROM classes WHERE subject = 'Underwater Basket Weaving'),
    (SELECT id FROM students WHERE first_name = 'Kristjan')),
  ((SELECT id FROM classes WHERE subject = 'Light Treason'),
    (SELECT id FROM students WHERE first_name = 'John')),
  ((SELECT id FROM classes WHERE subject = 'Happiness'),
    (SELECT id FROM students WHERE first_name = 'Jordon')),
  ((SELECT id FROM classes WHERE subject = 'Light Treason'),
    (SELECT id FROM students WHERE first_name = 'Mark')),
  ((SELECT id FROM classes WHERE subject = 'Flossing'),
    (SELECT id FROM students WHERE first_name = 'Nathan')),
  ((SELECT id FROM classes WHERE subject = 'Underwater Basket Weaving'),
   (SELECT id FROM students WHERE first_name = 'Brandon')),
  ((SELECT id FROM classes WHERE subject = 'Happiness'),
    (SELECT id FROM students WHERE last_name = 'Collier')),
  ((SELECT id FROM classes WHERE subject = 'Underwater Basket Weaving'),
    (SELECT id FROM students WHERE last_name = 'Miller')),
  ((SELECT id FROM classes WHERE subject = 'Light Treason'),
    (SELECT id FROM students WHERE last_name = 'Collier')),
  ((SELECT id FROM classes WHERE subject = 'Happiness'),
    (SELECT id FROM students WHERE first_name = 'Alias')),
  ((SELECT id FROM classes WHERE subject = 'Light Treason'),
    (SELECT id FROM students WHERE last_name = 'Nye')),
  ((SELECT id FROM classes WHERE subject = 'Flossing'),
    (SELECT id FROM students WHERE last_name = 'Glassford')),
  ((SELECT id FROM classes WHERE subject = 'Light Treason'),
    (SELECT id FROM students WHERE last_name = 'Harings')),
  ((SELECT id FROM classes WHERE subject = 'Happiness'),
    (SELECT id FROM students WHERE first_name = 'Shane')),
  ((SELECT id FROM classes WHERE subject = 'Light Treason'),
    (SELECT id FROM students WHERE last_name = 'Pando')),
  ((SELECT id FROM classes WHERE subject = 'Flossing'),
    (SELECT id FROM students WHERE first_name = 'Allen'));
